import { Button, Typography, TextField, Alert } from "@mui/material";
import { Stack } from "@mui/system";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import Cookies from "universal-cookie";
import { login } from "../src/api/api";

const cookies = new Cookies();

import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [error, setError] = useState(false);

  const doLogin = () => {
    login(email)
      .then((res) => {
        if (res.data) {
          const token = res.data[0].token || null;
          if (token !== null) {
            cookies.set("token", token);
            router.push("/products");
          } else {
            setError(true);
          }
        }
      })
      .catch(() => {
        setError(true);
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <Stack spacing={2}>
          <Typography variant="h3">Login</Typography>
          {error && <Alert severity="error">Error</Alert>}
          <TextField
            id="outlined-basic"
            label="Email"
            variant="outlined"
            onChange={(event) => {
              setEmail(event.target.value);
            }}
          />
          <Button
            variant="contained"
            onClick={() => {
              doLogin();
            }}
          >
            Login
          </Button>
        </Stack>
      </main>
    </div>
  );
}
